name: Bot Test

on:
  issue_comment:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Inspect payload
        run: cat "$GITHUB_EVENT_PATH"
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Run Python
        run: python bot.py