name: Bot Test

on:
  issue_comment:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Inspect payload
        run: cat "$GITHUB_EVENT_PATH"

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Check repo files
        run: ls -R

      - name: Run Python bot
        run: python bot.py